name: Deploy AngularJS

on:
  workflow_dispatch:
  push:
    branches: 
      - main

env:
  AZURE_WEBAPI_NAME: todowebappv1

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install dependencies and build
      run: | 
           npm install
           npm run build --prod
      working-directory: ./Client

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPI_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_frontend }}
        package: ./Client/dist/to-do
